# Generated by Django 3.2.4 on 2021-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='WHAT IS OUR GOAL?', max_length=200)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
