# Generated by Django 3.2.4 on 2021-07-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
