# Generated by Django 3.2.4 on 2021-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_faqs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
