# Generated by Django 3.1.7 on 2021-07-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210704_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestions',
            name='subquestion',
        ),
        migrations.AddField(
            model_name='subquestions',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.faqs'),
        ),
    ]
