# Generated by Django 3.1.7 on 2021-07-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210704_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestions',
            old_name='department',
            new_name='subquestion',
        ),
    ]
