# Generated by Django 3.2.4 on 2021-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210711_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
