# Generated by Django 3.1.7 on 2021-07-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210704_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestions',
            name='subquestion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.faqs'),
        ),
    ]
