# Generated by Django 3.1.7 on 2021-07-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210704_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestions',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='subquestions',
            name='subquestion',
        ),
        migrations.CreateModel(
            name='Interconnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.faqs')),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.subquestions')),
            ],
        ),
        migrations.AddField(
            model_name='subquestions',
            name='subquestion',
            field=models.ManyToManyField(blank=True, max_length=200, through='events.Interconnector', to='events.FAQs'),
        ),
    ]
